### ISSUE TITLE
预览视图报错

### ISSUE THREAD

**Issue by feng241x** [xiaopujun/light-chaser#12]
1.新建一个基础色块和柱状图组件，创建分组。
2.复制分组
3.选中2个分组再次复制，如此反复，铺满画布。
4.保存后预览。
错误提示：
`TypeError: Cannot read properties of undefined (reading '0')
    at ComponentContainer.render (index-ed455431.js:1429:89480)`

**Comment by xiaopujun** [comment]
Already filed for fix by #9
