### ISSUE TITLE
图标 禁用 X/Y轴 后 应用全局主题 报错

### ISSUE THREAD

**Issue by feng241x** [xiaopujun/light-chaser#14]
Uncaught TypeError: Cannot read properties of undefined (reading 'fill')
at AntdCommonLineController.updateTheme (index-197fe089.js:1403:80925)

**Comment by xiaopujun** [comment]
> Uncaught TypeError: Cannot read properties of undefined (reading 'fill') at AntdCommonLineController.updateTheme (index-197fe089.js:1403:80925)

请确认问题是否依然存在。若问题已修复，我将关闭issues。
