### ISSUE TITLE
组件不兼容 contenteditable?

### ISSUE THREAD

**Issue by emilymansw** [xiaopujun/light-chaser#17]
请教一下，像base-text那种简单组件能实现contenteditable 吗？

**Comment by xiaopujun** [comment]
> 请教一下，像base-text那种简单组件能实现contenteditable 吗？

能否描述下具体效果？是类似双击后就进入编辑模式这种效果嘛？

**Comment by emilymansw** [comment]
像这样https://daybrush.com/moveable/storybook/?path=/story/options--options-drag-focused-input
我在BPMovable加了 dragFocusedInput={true}，然后在BaseTextComponent 加上ref 用上onDoubleClick={() =>  ref.current!.focus()} 是可以直接编辑内容， 可是不知道要怎去更新组件配置

**Comment by xiaopujun** [comment]
> BPMovable

BPMovable? 这个是蓝图节点的拖拽组件，需要在蓝图上二次开发吗？还是指的DesignerMovable？ 如果是想达到类似双击文字直接进入文字编辑模式的效果。下一个版本会支持 @emilymansw

**Comment by xiaopujun** [comment]
light chaser v1.0.0已发布，可体验文本组件，是否满足上述的editable效果 @emilymansw
