### ISSUE TITLE
画布滚动,以及可以支持缩放功能

### ISSUE THREAD

**Issue by zhangle1** [xiaopujun/light-chaser#18]
这个我跑了下项目好像并没有发现有实现

**Comment by xiaopujun** [comment]
编辑模式下拖拽和缩放使用如下方法操作：
![image](https://github.com/xiaopujun/light-chaser/assets/38376350/3e4cafd1-358a-4521-8bfe-40341f3962c6)

预览模式下画布可以选择对应的适配模式：
![image](https://github.com/xiaopujun/light-chaser/assets/38376350/e93572f1-4ac9-4cbd-8307-4f45b521c811)

@zhangle1

**Comment by xiaopujun** [comment]
> 这个我跑了下项目好像并没有发现有实现

请确认下问题是否依然存在呢？

**Comment by zhangle1** [comment]
可以的 是我的问题 没用快捷键
