### ISSUE TITLE
需求,增加前端维度和度量控制组件  在数据提取和 映射之间 ,提供快捷操作的方式

### ISSUE THREAD

**Issue by zhangle1** [xiaopujun/light-chaser#19]
我可以移植一些开源框架java代码过来提供相关的能力

**Comment by xiaopujun** [comment]
> 我可以移植一些开源框架java代码过来提供相关的能力

后端开源仓库可参考（技术栈同为java）：https://github.com/xiaopujun/light-chaser-server

增加前端维度和度量控制组件没有很理解，可否举个例子或者提供类似的场景说明

**Comment by zhangle1** [comment]
https://study.sf.163.com/documents/read/FAQ/tbz03

目前框架的作法是通过 直接连http,jdbc的方式去直接读取数据并返回json ,  那么可以把这部分做细一点 抽象成 resource->dataset(这里可以读取到实际数据列的信息属性(string,value,date等等)) , 打个比方表格数据有学生姓名,数学分数,语文分数->那么可以通过前端组件拖拽的方式将row行数据拖拽到-> 维度(学生姓名), 度量(数学分数,语文分数) ->chartMap->实际映射出来就是
xAxist['张三','李四']   seriesMathData[50,60] seriesChineseData[50,60]   就是可以在映射到echartOption ->datasetView->resource,
这几层之间把类型补齐,  datasetView 也可以在这里(做数据的聚合,计算等等)

**Comment by xiaopujun** [comment]
> https://study.sf.163.com/documents/read/FAQ/tbz03
> 
> 目前框架的作法是通过 直接连http,jdbc的方式去直接读取数据并返回json , 那么可以把这部分做细一点 抽象成 resource->dataset(这里可以读取到实际数据列的信息属性(string,value,date等等)) , 打个比方表格数据有学生姓名,数学分数,语文分数->那么可以通过前端组件拖拽的方式将row行数据拖拽到-> 维度(学生姓名), 度量(数学分数,语文分数) ->chartMap->实际映射出来就是 xAxist['张三','李四'] seriesMathData[50,60] seriesChineseData[50,60] 就是可以在映射到echartOption ->datasetView->resource, 这几层之间把类型补齐, datasetView 也可以在这里(做数据的聚合,计算等等)

将会考虑这样的方式细化软件这方面的能力，如果愿意加入开发，可留下联系方式，我们详细沟通，会优先在开源后端上尝试验证该方案

**Comment by zhangle1** [comment]
可以的 大佬可以加我微信happyzhang131
