### ISSUE TITLE
MAC上无法删除蓝图节点

### ISSUE THREAD

**Issue by AlenYing** [xiaopujun/light-chaser#29]
![image](https://github.com/user-attachments/assets/833bc967-15f3-44c2-8c58-74b1f1691352)
尝试过回退、control+z等都无法删除蓝图节点

**Comment by xiaopujun** [comment]
你好，感谢提交issus。Mac系统的快捷键都有适配的，Mac中的删除快捷键为command + 退格键。主设计器与蓝图设计器均使用该快捷键。可以看下左下角的快捷键说明。

**Comment by AlenYing** [comment]
感谢。尝试成功。
