### ISSUE TITLE
组件拖不进画布，画布缩放无法设置，开启栅格无效等等

### ISSUE THREAD

**Issue by alindas** [xiaopujun/light-chaser#3]

**Comment by alindas** [comment]
本地运行发现上述诸多问题…

**Comment by xiaopujun** [comment]
拉取master分支。双击添加组件。关注今天的设计器操作文档更新

**Comment by xiaopujun** [comment]
> 

拉取master分支。双击添加组件。关注今天的设计器操作文档更新

**Comment by xiaopujun** [comment]
> 本地运行发现上述诸多问题…

![image](https://github.com/xiaopujun/light-chaser/assets/38376350/5525e47d-4cae-4031-9ee6-727ce1f23938)
