### ISSUE TITLE
蓝图条件判断是否能够引入别的组件数据

### ISSUE THREAD

**Issue by AlenYing** [xiaopujun/light-chaser#30]
希望实现功能：多次点击某一文本组件，实现另一个组件的显示隐藏状态切换。
思路是：点击文本组件时，判断受控组件显示状态，如显示则隐藏，如隐藏则显示。
因此希望了解是否能够在条件判断中对组件状态进行判断
感谢。
![image](https://github.com/user-attachments/assets/abbc2891-56d6-497a-95dc-9811f10fc24c)

**Comment by xiaopujun** [comment]
针对特定组件可以通过逻辑节点实现该效果，在逻辑处理节点中维护一个全局变量，每次点击时对全局变量取反。将逻辑节点处理的结果传递给条件判断节点。 最后通过判断是否满足条件控制目标组件的显示与隐藏

**Comment by xiaopujun** [comment]
在蓝图节点执行过程中引入其他组件的数据，后续会考虑支持这一点。目前要实现该功能可以在组件初始化完成时，将组件数据抛出为全局变量，挂载到window下

**Comment by AlenYing** [comment]
了解
