### ISSUE TITLE
需求请教

### ISSUE THREAD

**Issue by AlenYing** [xiaopujun/light-chaser#31]
我在团队中是产品经理的角色，经过这几天的演示，领导对于单页面呈现的效果比较满意，但提出了几点新的需求，我希望请教您获得一些建议。我会提供一些我的思路，您可以参考或提出完全新的思路，最终希望您告知我哪些是当前系统中可以实现的功能，哪些是您预期会开发的功能，哪些是需要我们研发支持开发的功能。
1、 多页面切换：点击不同的按钮，显示不同的数据面板（如：教学数据，设备数据，人流数据）。目前编辑器中主要支持的还是单页面的编辑和呈现。我通过蓝图的逻辑控制可以通过操作元素组的显示隐藏进行切换。一个思路是参照SPA的路由实现，动态渲染dom。一个思路是在一个项目中插入iframe，点击不同的按钮嵌入不同的链接。此情况有如下问题：
1.1 页面如何导出为可部署的HTML,js,css文件。目前系统仅支持预览，导出也是json格式。是否能够实现导出一个可部署到服务器的内容，直接通过nginx就可以实现访问了。
2、单页面间组件数据联动：如面板中心有一个3D/2D的平面图，点击对应区域，四周的数据看板展示对应区域的数据。目前系统中的文字和图片和色块无法支持与数据联动。如UI开发了一个设备信息的看板（如图例），我希望通过一个列表动态渲染信息。这个是不是只能通过二次开发新的组件实现。
需求优先级：
1、页面导出发布功能；
2、组件间联动；
3、动态渲染dom。

感谢

**Comment by xiaopujun** [comment]
你好，感谢提交issue，针对你上面提到的问题：
1. 据我目前得到的信息。页面的导出发布不是一个简单的增量功能，需要在设计器设计的过程中就要处理好代码结构，类似于数据埋点一样，在导出的时候根据设计好的代码结构进行源码生成。最终还需要编译生成最终的源码。目前light chaser的设计上没有按照这个思路设计，使用时需要配合light chaser本身进行设计和页面展示，因此暂时无法提供该功能的支持。如果你有更好的源码生成方案，我们可以相互交流，兴许能产生一个更好的结果。生成源码我的意思是直接生成设计好页面的js、css、html。
2. 组件间联动：这个取决于每个组件接入蓝图的细化程度，lc的蓝图理论上支持任何形式的web事件。因此如果需要更细化的事件间联动，针对开源版可以自行二次开发扩展原有组件。任何组件皆是如此，不管2d或者3d，要做的事情仅是将自己的事件触发抛出，交给蓝图。剩下的事件在各组件之间的传递和处理，蓝图会根据节点的配置自动完成
3. 针对多页面切换功能，开源版未作支持，pro版有大屏组件可以实现。可以理解为在A大屏中直接引用B大屏。如果你的需求是按钮1、按钮2、按钮3分别对应了教学数据、设备数据、人流数据。那么只需在点击按钮1的时候使用大屏组件连接到教学数据即可，其他面板的切换以此类推。
4. 针对pro版本，在开源版的基础上提供了更好的代码设计，支持自定义g2系列图表、echarts系列图表、支持大屏组件、支持服务器组件。

以上描述希望能解答你的疑问。如有问题，欢迎随时交流

**Comment by AlenYing** [comment]
因为我们面对的是商业项目场景，需要持久稳定的呈现。那么我理解现在如果不做任何二次开发，系统支持部署到客户方的方式只有部署LC然后通过预览进行展示是吗？

**Comment by xiaopujun** [comment]
是的

**Comment by AlenYing** [comment]
pro版本目前能够支持体验吗？

**Comment by xiaopujun** [comment]
有的，可以留下邮箱或者联系方式，我单独给你提供下账号

**Comment by AlenYing** [comment]
755453949@qq.com
感谢

**Comment by xiaopujun** [comment]
已发送邮件，请注意查收

**Comment by xiaopujun** [comment]
你好，针对上面提到的源码导出功能，对于设计器而言，你是希望直接导出html、css、js。直接以文件方式就能运行的效果吗？对于使用到数据库数据的组件是必须依赖后端的，这点不知道你是否有考虑。
