### ISSUE TITLE
联动展示需求

### ISSUE THREAD

**Issue by AlenYing** [xiaopujun/light-chaser#33]
项目中需求如下：在一个地图iframe中有多个点位，点击某个点位后，需要更新图表及数字为点击点位的数据。

现问题如下：iframe组件本身没有点击事件，点击点位可以抛出message事件与外层交互。然而，我无法通过蓝图事件触发数据更新；数字组件可以用dom+fetch的形式强行实现；但图表就没办法了。

我尝试了dom模拟点击事件，但模拟点击事件无法触发蓝图中的点击。

不知道您有什么思路吗

**Comment by xiaopujun** [comment]
![image](https://github.com/user-attachments/assets/d245bed2-7653-4701-8f9f-fbbe8a8273b0)

根据上面的接入，触发蓝图事件核心有三个参数。组件id、事件id、事件参数。如果你们经过了自定义，那么完全可以将蓝图触发器抛出到window，然后在任意时候自动或手动的触发蓝图事件。 以你上面的点击ifrme内容触发message到外层容器。可以在外层维护一个消息池对象。 每当更新消息池中内容的时候根据传递进来的message通过抛出的蓝图事件触发器手动的的执行蓝图事件。  如果你要更新图表数据，则可以匹配到对应message后修改组件配置，再重新渲染组件

**Comment by xiaopujun** [comment]
部署教程：https://xiaopujun.github.io/light-chaser-doc/#/deploy/deploy_pro


从QQ邮箱发来的超大附件

0.0.2.zip (326.97M, 2024年10月22日 11:01 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0a3865619709a38a947ae5271561014e4c4c04035556035619095459504c5050040948570554024c570e5c0702050b0755095059336833511a084b531d1b5a113405&t=exs_ftn_download&code=48ea3a3a

**Comment by AlenYing** [comment]
感谢
