### ISSUE TITLE
如果单独的select 切换参数后请求参数发生变化 然后如何停止原来轮询请求 更新参数后重新请求组件重新渲染

### ISSUE THREAD

**Issue by kkyang63** [xiaopujun/light-chaser#34]
如果单独的select 切换参数后请求参数发生变化 然后如何停止原来轮询请求 更新参数后重新请求组件重新渲染
![image](https://github.com/user-attachments/assets/82f5c462-7b0a-4fcc-b5a3-691d2cfead6c)

**Comment by xiaopujun** [comment]
![image](https://github.com/user-attachments/assets/e9abd515-9683-475e-812b-f1ac04a7053e)
如上所示，每个组件的controller实例都会拥有一个轮询请求定时器interval，如果你要手动停止，则需要先获取组件的controller实例，然后调用clearTimeout()方法关闭轮询。 你可以在设计器加载数据的时候将controller实例暴露到window中，并在需要的时候使用它。所有操作组件的动作都应该从controller实例出发，而不是直接操作组件本身

![image](https://github.com/user-attachments/assets/77f9e12b-e2a6-4abd-8189-6b4b8f21e867)

**Comment by kkyang63** [comment]
> ![image](https://private-user-images.githubusercontent.com/38376350/370164465-e9abd515-9683-475e-812b-f1ac04a7053e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQxOTEsIm5iZiI6MTcyNzE2Mzg5MSwicGF0aCI6Ii8zODM3NjM1MC8zNzAxNjQ0NjUtZTlhYmQ1MTUtOTY4My00NzVlLTgxMmItZjFhYzA0YTcwNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDdhNTcwYjI1NDdlODM5NGI4ODcyNGE3OTBiNDNmMWNhNzU3ZDJhYzdhMzJmZmRiYWM3N2RkYzU5OTYzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uGcz3dg0C044Dbi_mSXqiNNKwOSVyjWORn_g7rY2xPk) 如上所示，每个组件的controller实例都会拥有一个轮询请求定时器interval，如果你要手动停止，则需要先获取组件的controller实例，然后调用clearTimeout()方法关闭轮询。 你可以在设计器加载数据的时候将controller实例暴露到window中，并在需要的时候使用它。所有操作组件的动作都应该从controller实例出发，而不是直接操作组件本身
> 
> ![image](https://private-user-images.githubusercontent.com/38376350/370165701-77f9e12b-e2a6-4abd-8189-6b4b8f21e867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQxOTEsIm5iZiI6MTcyNzE2Mzg5MSwicGF0aCI6Ii8zODM3NjM1MC8zNzAxNjU3MDEtNzdmOWUxMmItZTJhNi00YWJkLTgxODktNmI0YjhmMjFlODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjA4NmYzYWVmM2FmY2NjODM5M2FmOGIxMWY3YmJmMGRjOTRmNmY4NjFmZGQzZjRlOWNhZTI3ZDRkMTlkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ddep4WTgyiDsYnBQeYj8Y29BNpSkJS9qY6WluswAy0)
感谢

**Comment by kkyang63** [comment]
感谢
