### ISSUE TITLE
![image](https://github.com/user-attachments/assets/e9abd515-9683-475e-812b-f1ac04a7053e)

### ISSUE THREAD

**Issue by kkyang63** [xiaopujun/light-chaser#36]
![image](https://github.com/user-attachments/assets/e9abd515-9683-475e-812b-f1ac04a7053e)
如上所示，每个组件的controller实例都会拥有一个轮询请求定时器interval，如果你要手动停止，则需要先获取组件的controller实例，然后调用clearTimeout()方法关闭轮询。 你可以在设计器加载数据的时候将controller实例暴露到window中，并在需要的时候使用它。所有操作组件的动作都应该从controller实例出发，而不是直接操作组件本身

![image](https://github.com/user-attachments/assets/77f9e12b-e2a6-4abd-8189-6b4b8f21e867)

_Originally posted by @xiaopujun in https://github.com/xiaopujun/light-chaser/issues/34#issuecomment-2370347379_

**Comment by kkyang63** [comment]
![image](https://github.com/user-attachments/assets/dfa896ef-2459-4e39-828e-bca614c51489)
我这个版本是这样子的

**Comment by xiaopujun** [comment]
这个应该不是最新master分支的代码，如果可以，请更新master分支代码。如果需要继续在当前分支二次开发，则思路上是一致的。controller实例会在上面初始化执行完成之后，在每个组件渲染完毕时，被赋值到layerManager（历史版本为layerStore）的compController属性中，因此仅需将compController暴露给window即可
