### ISSUE TITLE
分组添加api请求配置， 请求数据共享

### ISSUE THREAD

**Issue by kkyang63** [xiaopujun/light-chaser#38]
![image](https://github.com/user-attachments/assets/64005618-1384-4dd0-9bda-b0fec5274014)

配置已经在在并保存， view是不发请求

**Comment by kkyang63** [comment]
预览时没请求 需要做哪些操作

**Comment by xiaopujun** [comment]
![image](https://github.com/user-attachments/assets/aa83dc12-3dc9-47b1-91c5-8d37a67d6b70)
调试AbstractDesignerController中的请求数据接口，这个页面看着被二次开发过的吧？

**Comment by kkyang63** [comment]
加了返回结果处理函数， 你这边有没有好的方式

**Comment by xiaopujun** [comment]
二次开发的根据上面的截图，调试下请求是否发出了，发出后数据是否正常走到你自定义的处理函数中。结果集处理标准也是用的自定义过滤器，和你这个没有太大区别，

**Comment by kkyang63** [comment]
我这个主要是要定义好处理函数  根据名称引用  之前存函数字符串，存储后没转过过来

**Comment by xiaopujun** [comment]
这种只能debug调试，只看现象没法定位问题原因
