### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by vannvan** [xiaopujun/light-chaser#4]
看的出来作者还在不断的完善功能哈，有一说一已经很强大了，有几个初体验的小建议：

1. `eslint` 没在 `dependencies`里 ，启动会报错，虽然可以自己安装，但是开源的话，这块完善一点还是比较好(与第2个问题应该是相关的)

2. 会报这个错，我采取的方式是新建`.env`写入`SKIP_PREFLIGHT_CHECK=true`解决了
![image](https://github.com/xiaopujun/light-chaser/assets/43501134/4a77e71a-1d19-4a86-bd59-e36cbb8f279f)

 3. `iframe`影响了图层的所有事件，手动加了`pointer-events:none`才生效，还没明确代码层面的原因，但是其他人上手如果半天点不动可能就劝退了(设计器内部也会影响到)。

![image](https://github.com/xiaopujun/light-chaser/assets/43501134/0a202301-9c39-4757-ad43-8b11daca79be)

4. 文字颜色
![image](https://github.com/xiaopujun/light-chaser/assets/43501134/dd2fee2f-9a78-4777-a0e5-35e6432530fa)

5. 交互问题
<img width="1006" alt="image" src="https://github.com/xiaopujun/light-chaser/assets/43501134/028f28a7-d47d-473e-8838-f3dcc1c69baa">

左侧`组件列表`的组件进入画布的交互个人认为更好的方式有两种 1. 单击进入画布，但是一般在正中心 2. 拖拽进画布，目前是双击，湿了几次才发现(同时默认添加在左上角，目前组件列表就遮挡了画布一部分，体验不是很好～)

另外画布中的组件删除，目前好像是`delete`删除，按道理`backspace`更符合大多数的使用习惯

初次体验，以上建议仅供参考哈，如有不对之处还望担待，还会深度体验～

**Comment by xiaopujun** [comment]
> 看的出来作者还在不断的完善功能哈，有一说一已经很强大了，有几个初体验的小建议：
> 
> 1. `eslint` 没在 `dependencies`里 ，启动会报错，虽然可以自己安装，但是开源的话，这块完善一点还是比较好(与第2个问题应该是相关的)
> 2. 会报这个错，我采取的方式是新建`.env`写入`SKIP_PREFLIGHT_CHECK=true`解决了
>    ![image](https://user-images.githubusercontent.com/43501134/249988950-4a77e71a-1d19-4a86-bd59-e36cbb8f279f.png)
> 3. `iframe`影响了图层的所有事件，手动加了`pointer-events:none`才生效，还没明确代码层面的原因，但是其他人上手如果半天点不动可能就劝退了(设计器内部也会影响到)。
> 
> ![image](https://user-images.githubusercontent.com/43501134/249990499-0a202301-9c39-4757-ad43-8b11daca79be.png)
> 
> 4. 文字颜色
>    ![image](https://user-images.githubusercontent.com/43501134/249990674-dd2fee2f-9a78-4777-a0e5-35e6432530fa.png)
> 5. 交互问题
> 
> <img alt="image" width="1006" src="https://user-images.githubusercontent.com/43501134/249991041-028f28a7-d47d-473e-8838-f3dcc1c69baa.png">
> 左侧`组件列表`的组件进入画布的交互个人认为更好的方式有两种 1. 单击进入画布，但是一般在正中心 2. 拖拽进画布，目前是双击，湿了几次才发现(同时默认添加在左上角，目前组件列表就遮挡了画布一部分，体验不是很好～)
> 
> 另外画布中的组件删除，目前好像是`delete`删除，按道理`backspace`更符合大多数的使用习惯
> 
> 初次体验，以上建议仅供参考哈，如有不对之处还望担待，还会深度体验～

问题1和2：目前我本地没有发现这个问题，会找一些其他开发者验证下具体问题和原因
问题3：这个目前看是脚手架和ts的版本问题，目前刷新后可以暂时解决开发时的问题。后续会重新考虑项目的构建方式，可能会脱离脚手架（这个还在研究中，哈哈...)
问题4：会在最近的修改中调整
问题5：目前考虑，添加组件不会是很频繁的操作，因此仅用单机可能会导致误触发。暂时仍然使用双击的方式。拖拽引入后续会考虑支持

感谢您的反馈

**Comment by xiaopujun** [comment]
light chaser 已发布新功能，欢迎体验：https://xiaopujun.github.io/light-chaser-app/#

**Comment by xiaopujun** [comment]
> 看的出来作者还在不断的完善功能哈，有一说一已经很强大了，有几个初体验的小建议：
> 
> 1. `eslint` 没在 `dependencies`里 ，启动会报错，虽然可以自己安装，但是开源的话，这块完善一点还是比较好(与第2个问题应该是相关的)
> 2. 会报这个错，我采取的方式是新建`.env`写入`SKIP_PREFLIGHT_CHECK=true`解决了
>    ![image](https://user-images.githubusercontent.com/43501134/249988950-4a77e71a-1d19-4a86-bd59-e36cbb8f279f.png)
> 3. `iframe`影响了图层的所有事件，手动加了`pointer-events:none`才生效，还没明确代码层面的原因，但是其他人上手如果半天点不动可能就劝退了(设计器内部也会影响到)。
> 
> ![image](https://user-images.githubusercontent.com/43501134/249990499-0a202301-9c39-4757-ad43-8b11daca79be.png)
> 
> 4. 文字颜色
>    ![image](https://user-images.githubusercontent.com/43501134/249990674-dd2fee2f-9a78-4777-a0e5-35e6432530fa.png)
> 5. 交互问题
> 
> <img alt="image" width="1006" src="https://user-images.githubusercontent.com/43501134/249991041-028f28a7-d47d-473e-8838-f3dcc1c69baa.png">
> 左侧`组件列表`的组件进入画布的交互个人认为更好的方式有两种 1. 单击进入画布，但是一般在正中心 2. 拖拽进画布，目前是双击，湿了几次才发现(同时默认添加在左上角，目前组件列表就遮挡了画布一部分，体验不是很好～)
> 
> 另外画布中的组件删除，目前好像是`delete`删除，按道理`backspace`更符合大多数的使用习惯
> 
> 初次体验，以上建议仅供参考哈，如有不对之处还望担待，还会深度体验～

light chaser 已发布新功能，欢迎体验：https://xiaopujun.github.io/light-chaser-app/#
