### ISSUE TITLE
建议开源项目中去除百度统计相关代码

### ISSUE THREAD

**Issue by Houtx** [xiaopujun/light-chaser#6]
![image](https://github.com/xiaopujun/light-chaser/assets/17922172/fb0da7e8-6a34-4421-b523-6b4afa8c9a16)

**Comment by xiaopujun** [comment]
已去除，下个版本将没有统计脚本

**Comment by xiaopujun** [comment]
> ![image](https://user-images.githubusercontent.com/17922172/276508944-fb0da7e8-6a34-4421-b523-6b4afa8c9a16.png)

已去除，下个版本将没有统计脚本
