### ISSUE TITLE
图层分组缺陷

### ISSUE THREAD

**Issue by feng241x** [xiaopujun/light-chaser#9]
文字图层修改内容后 和其他图层 编组会丢失内容！
此时保存预览报错！
index-ed455431.js:39 TypeError: Cannot read properties of undefined (reading '0')
    at ComponentContainer.render (index-ed455431.js:1429:89480)

**Comment by xiaopujun** [comment]
更新master分支后查看问题是否仍然存在

**Comment by xiaopujun** [comment]
> 文字图层修改内容后 和其他图层 编组会丢失内容！ 此时保存预览报错！ index-ed455431.js:39 TypeError: Cannot read properties of undefined (reading '0') at ComponentContainer.render (index-ed455431.js:1429:89480)

更新master分支后查看问题是否仍然存在，若问题已得到解决，请反馈。我将关闭本issue

**Comment by feng241x** [comment]
这个问题已解决
